### ISSUE TITLE
When opening Combined Authority area, no additional layers area available

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/EValuator#24]
We either:

a) Duplicate the data per MSOA
b) (quick and dirty) resolve down to Local Authority for MSOA and link to that on the link
c) Something very clever yet fraught with data - aggregating data in the front-end...

Discuss (b is probably easier)

**Comment by slowe** [comment]
I think all the layers are updated now for each area (Local Authorities and Combined Authorities).

**Comment by gilesdring** [comment]
Yes - seems to work

**Comment by gilesdring** [comment]
We're probably on GitHub's watch list - I suspect a 379M pages site is beyond their expectation!

**Comment by slowe** [comment]
@gilesdring Where do you get 379M from?
